name: Continuous Integration

on:
  push:
    branches:
      - dev
      - main
      - develop
  pull_request:
    branches:
      - main
      - dev
      - develop

permissions:
  checks: write
  contents: read
  pull-requests: write
  actions: read
  statuses: write

env:
  NODE_VERSION: '20'

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install root dependencies
        run: npm ci

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run frontend linter
        working-directory: ./frontend
        run: npm run lint

      - name: Run frontend tests
        working-directory: ./frontend
        run: npm run test:ci || echo "No tests configured yet"

      - name: Build frontend project
        working-directory: ./frontend
        run: npm run build

      - name: Upload frontend build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build-${{ github.sha }}
          path: frontend/out/
          retention-days: 7

      - name: Install backend dependencies
        working-directory: ./backend/functions
        run: npm ci

      - name: Run backend linter
        working-directory: ./backend/functions
        run: npm run lint

      - name: Build backend functions
        working-directory: ./backend/functions
        run: npm run build

      - name: Upload backend build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-build-${{ github.sha }}
          path: backend/functions/lib/
          retention-days: 7

      - name: Run comprehensive validation
        run: npm run validate
