# DISABLED: E2E Tests - Using local testing instead
# This workflow has been disabled in favor of local testing approach
# Run E2E tests locally using: npm run local:accessibility, npm run local:performance
#
# To re-enable: uncomment the workflow below and remove this comment block
#
# Original workflow disabled on: July 23, 2025
# Reason: Moved to local-first development approach for faster feedback
#
# Local testing commands:
# - ./scripts/dev-check.sh (lint + build + quick test)
# - npm run local:accessibility (30s - includes E2E accessibility)
# - npm run local:performance (2min - includes E2E performance)
# - npm run local:smoke (30s - basic E2E functionality)
# - npm run local:debug (visual E2E debugging)

# This is a minimal valid workflow that does nothing (workflow is disabled)
name: "DISABLED - E2E Tests"
on:
  workflow_dispatch: # Only manual trigger, no automatic triggers

jobs:
  disabled-info:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Disabled Info
        run: |
          echo "ℹ️  This E2E workflow has been disabled in favor of local testing."
          echo "🚀 Use local testing instead:"
          echo "   ./scripts/dev-check.sh (lint + build + quick test)"
          echo "   npm run local:accessibility (30s - includes E2E)"
          echo "   npm run local:performance (2min - includes E2E)"
          echo "   npm run local:smoke (30s - basic E2E functionality)"
          echo "   npm run local:debug (visual E2E debugging)"

# Original workflow content has been moved to documentation
# To restore full workflow, see git history or DETAILED_DEVELOPMENT_WORKFLOW.md
