# DISABLED: Test & Quality Checks - Using local testing instead
# This workflow has been disabled in favor of local testing approach
# Run tests locally using: npm run local:accessibility, npm run local:performance
#
# To re-enable: uncomment the workflow below and remove this comment block
#
# Original workflow disabled on: July 23, 2025
# Reason: Moved to local-first development approach for faster feedback
#
# Local testing commands:
# - ./scripts/dev-check.sh (lint + build + quick test)
# - npm run local:accessibility (30s)
# - npm run local:performance (2min)
# - npm run local:smoke (30s)
# - npm run local:debug (visual debugging)

# This is a minimal valid workflow that does nothing (workflow is disabled)
name: "DISABLED - Test & Quality Checks"
on:
  workflow_dispatch: # Only manual trigger, no automatic triggers

jobs:
  disabled-info:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Disabled Info
        run: |
          echo "ℹ️  This workflow has been disabled in favor of local testing."
          echo "🚀 Use local testing instead:"
          echo "   ./scripts/dev-check.sh (lint + build + quick test)"
          echo "   npm run local:accessibility (30s)"
          echo "   npm run local:performance (2min)"
          echo "   npm run local:smoke (30s)"
          echo "   npm run local:debug (visual debugging)"

# Original workflow content has been moved to documentation
# To restore full workflow, see git history or DETAILED_DEVELOPMENT_WORKFLOW.md
